---
title: ''
params:
  id_municipio: 38001
  convocatoria: 201911
  url.cl_area: https://datos.canarias.es/api/estadisticas/structural-resources/v1.0/codelists/ISTAC/CL_AREA_ES70_COMARCAS/01.000/codes
  url.mapa: https://datos.canarias.es/catalogos/estadisticas/dataset/6dd8baf4-14f4-43a3-88b2-984d034c965c/resource/812f22ae-62a5-4cea-8052-b0269b1bd491/download/municipios_20170101.json
  url.mapa_2007: https://datos.canarias.es/catalogos/estadisticas/dataset/03f5044c-6d40-4c09-84db-eaf9d6681b48/resource/d765c56b-a67d-46e2-800e-5c9a1e9138f0/download/municipios_20170101_antes2007.json
  url.dist_mun: https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicatorsSystems/C00067A/indicatorsInstances/6daf4220-c08f-431c-8383-a0a7daa87da7
  url.congreso_201911: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000035/~latest.json?dim=MEDIDAS:VOTOS_VALIDOS_CANDIDATURA|RATIO_VOTOS_CANDIDATURA:TERRITORIO:35004|35010|35018|35024|35028|35029|35034|35003|35007|35014|35015|35017|35030|35001|35002|35005|35006|35008|35009|35011|35012|35013|35016|35019|35020|35021|35022|35023|35025|35026|35027|35031|35032|35033|38001|38004|38005|38006|38010|38011|38012|38015|38017|38018|38019|38020|38022|38023|38025|38026|38028|38031|38032|38034|38035|38038|38039|38040|38041|38042|38043|38044|38046|38051|38052|38002|38003|38021|38036|38049|38050|38007|38008|38009|38014|38016|38024|38027|38029|38030|38033|38037|38045|38047|38053|38013_2007|38048|38901&lang=es
  url.congreso_201904: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000026/~latest.json?&lang=es
  url.congreso_201606: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000009/~latest.json?&lang=es
  url.congreso_201512: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000007/~latest.json?&lang=es
  url.congreso_201111: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000002/~latest.json?&lang=es
  url.congreso_200803: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000016/~latest.json?&lang=es
  url.congreso_200403: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000017/~latest.json?&lang=es
  url.congreso_200003: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000018/~latest.json?&lang=es
  url.congreso_electores: http://www.gobiernodecanarias.org/istac/jaxi-istac/tabla.do?accion=jsonMtd&uuidConsulta=a73b11d9-02c6-49dd-bed4-1b21978d003b
output:
  html_document:
    df_print: paged
    css: styles/FICHA.css
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, error=FALSE)
```

```{r librerías, include=FALSE}
list.of.packages <- c("jsonlite", "ggplot2", "knitr", "data.table", "plotly", "plyr", "dplyr", "scales", "htmlwidgets", "sf", "fuzzyjoin", "xml2", "XML", "tidyverse", "tmap", "magrittr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
sapply(list.of.packages, require, character.only = TRUE)

signo <- function(value) {
  if (value > 0){sign <- "más"} else {sign <- "menos"}
  return(sign)
}

"%notin%" <- Negate("%in%")
```

```{r Convocatoria}
# Electores en Canarias en las elecciones Generales según convocatorias. Municipios por islas de Canarias.
data_electores <- fromJSON(params$url.congreso_electores)
convocatoria <- data.frame(code = as.integer(data_electores[["categories"]][["codes"]][[1]]),
                           convocatoria = data_electores[["categories"]][["labels"]][[1]],
                           order = as.integer(order(data_electores[["categories"]][["codes"]][[1]], decreasing = FALSE)))

convocatoria_actual <- convocatoria %>% filter(substring(code, 0,6) == params$convocatoria)
convocatoria_tva <- convocatoria[convocatoria$order == convocatoria[convocatoria_actual$code == convocatoria$code, ]$order - 1, ]
```

```{r Municipio actual}
CL_AREA <- as_list(read_xml(params$url.cl_area))

df_CL_AREA <- tibble::as_tibble(CL_AREA) %>% 
  unnest_wider('codes') %>%
  transform(name = lapply(name, '[[', 2)) %>% 
  unnest(cols = names(.)) %>%
  unnest(cols = names(.)) %>%
  readr::type_convert() %>%
  mutate(parent = gsub("^.*).", "", parent)) %>%
  select(code = id, value = name, parent)

df_CL_AREA_mun <- df_CL_AREA %>% 
  select(id = code, municipio = value, code = parent) %>%
  filter(substring(id, 0,2) != "ES") %>% 
  transform(id = if_else(substring(id, 0,5) == "38013",  "38013", id)) %>%
  filter(nchar(id) > 0 & !grepl("(", municipio, fixed = TRUE)) %>%
  left_join(df_CL_AREA, by="code") %>%
  select(id, municipio, code = parent, id_comarca = code, comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, code = parent, id_gran_comarca = code, gran_comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, code = parent, id_isla = code, isla = value) %>%
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, id_isla, isla, provincia = value)

municipio_actual <- df_CL_AREA_mun[df_CL_AREA_mun$id == params$id_municipio,]
```

```{r Normalización de municipios} 
recode_mun.from <- c("Oliva (La)", "Palmas de Gran Canaria (Las)", "Valsequillo", "Santa María de Guía", "Aldea de San Nicolás (La)", "Santa Lucía", "Pinar de El Hierro (El)", "Pinar de El Hierro, El", "Fuencaliente", "Llanos de Aridane (Los)", "Paso (El)", "Laguna (La)", "Rosario (El)", "Matanza de Acentejo (La)", "Sauzal (El)", "Victoria de Acentejo (La)", "Silos (Los)", "Tanque (El)", "Guancha (La)", "Orotava (La)", "Realejos (Los)", "San Miguel", "Vilaflor", "Güimar", "Icod de Los Vinos", "Puerto de La Cruz", "San Juan de La Rambla")
recode_mun.to <- c("La Oliva", "Las Palmas de Gran Canaria", "Valsequillo de Gran Canaria", "Santa María de Guía de Gran Canaria", "La Aldea de San Nicolás", "Santa Lucía de Tirajana", "El Pinar de El Hierro", "El Pinar de El Hierro", "Fuencaliente de La Palma", "Los Llanos de Aridane", "El Paso", "San Cristóbal de La Laguna", "El Rosario", "La Matanza de Acentejo", "El Sauzal", "La Victoria de Acentejo", "Los Silos", "El Tanque", "La Guancha", "La Orotava", "Los Realejos", "San Miguel de Abona", "Vilaflor de Chasna", "Güímar", "Icod de los Vinos", "Puerto de la Cruz", "San Juan de la Rambla")
recode_mun <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = recode_mun.from, to = recode_mun.to)
  df[,colname]
}
```

```{r Electores por residencia}
df_electores <- cbind(data.frame(do.call('rbind', data_electores[["data"]][["dimCodes"]])), data_electores[["data"]][["Valor"]])
colnames(df_electores) <- c('convocatoria', 'mun', 'residencia', 'valor')
df_electores$convocatoria <- factor(df_electores$convocatoria, levels=data_electores[["categories"]][["codes"]][[1]], labels=data_electores[["categories"]][["labels"]][[1]])
df_electores$mun <- factor(df_electores$mun, levels=data_electores[["categories"]][["codes"]][[2]], labels=data_electores[["categories"]][["labels"]][[2]])
df_electores$residencia <- factor(df_electores$residencia, levels=data_electores[["categories"]][["codes"]][[3]])
df_electores$valor <- as.numeric(df_electores$valor)
df_electores$mun <- recode_mun(df_electores, 'mun')

df_electores_mun <- df_electores %>%
  filter(mun == municipio_actual$municipio & convocatoria == convocatoria_actual$convocatoria) %>% 
  select(c(residencia, valor))

Num_Electores <- df_electores_mun %>% filter(residencia == "T") %>% select(valor) %>% as.numeric() %>% format(big.mark = ".", decimal.mark = ",")
Num_Electores_Canarias <- df_electores_mun %>% filter(residencia == "ES70") %>% select(valor) %>% as.numeric() %>% format(big.mark = ".", decimal.mark = ",")
Num_Electores_Extranjero <- df_electores_mun %>% filter(residencia == "ESZ") %>% select(valor) %>% as.numeric() %>% format(big.mark = ".", decimal.mark = ",")
```

```{r Resultados}
# data_congreso <- fromJSON(paste0("params$url.congreso_", params$convocatoria))
data_congreso_201911 <- fromJSON(params$url.congreso_201911)

df_congreso <- data.frame(
  medida = rep(data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
               each = length(data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                      length(data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  mun = rep(data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  candidatura = data_congreso_201911[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
  valor = unlist(strsplit(data_congreso_201911[["data"]][["observations"]], split = " | ", fixed = TRUE)))
df_congreso$valor <- as.numeric(df_congreso$valor)
df_congreso <- df_congreso %>% transform(mun = if_else(mun == "38013_2007",  "38013", mun))

df_partido <- data.frame(
  candidatura = data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["id"]],
  name_partido = c(data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[1]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[2]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[3]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[4]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[5]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[6]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[7]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[8]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[9]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[10]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[11]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[12]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[13]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[14]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[15]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[16]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[17]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[18]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[19]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[20]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[21]][["value"]],
                   data_congreso_201911[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[22]][["value"]]))

df_congreso_mun <- df_congreso %>% 
  left_join(df_partido, by="candidatura") %>%
  filter(mun == params$id_municipio)
partido_mas_votado <- df_congreso_mun %>% filter(medida == "VOTOS_VALIDOS_CANDIDATURA" & substring(candidatura, 0,1) == "P") %>% top_n(1, valor) %>% select(name_partido) %>% 
  as.character()
df_plot_ <- df_congreso_mun %>% filter(substring(candidatura, 0,1) == "G") %>% arrange(valor) %>% select(c(medida, name_partido, valor))
df_plot_ <- df_plot_ %>% spread(medida, valor) %>% select(name_partido, VOTOS_VALIDOS_CANDIDATURA, RATIO_VOTOS_CANDIDATURA)
df_plot <- df_plot_ %>% rbind(c("", sum(df_plot_$VOTOS_VALIDOS_CANDIDATURA)))
df_plot$VOTOS_VALIDOS_CANDIDATURA <- as.numeric(df_plot$VOTOS_VALIDOS_CANDIDATURA)
df_plot$RATIO_VOTOS_CANDIDATURA <- as.numeric(df_plot$RATIO_VOTOS_CANDIDATURA)
df_plot <- df_plot %>% mutate(porcentaje = df_plot$VOTOS_VALIDOS_CANDIDATURA / sum(df_plot$VOTOS_VALIDOS_CANDIDATURA) * 100) %>% arrange(VOTOS_VALIDOS_CANDIDATURA)

df_plot$name_partido <- ordered(df_plot$name_partido, levels = df_plot$name_partido[6:1])

df_plot <- df_plot %>% transform(hovertext = paste0(
    "<b>", name_partido, " </b>",
    "<br>", trimws(format(VOTOS_VALIDOS_CANDIDATURA, big.mark = ".", decimal.mark = ",")), " votos", 
    " (", trimws(format(round(RATIO_VOTOS_CANDIDATURA, 1), big.mark = ".", decimal.mark = ",")), "%)"
  )
)

g_congreso_mun <- plot_ly(df_plot, labels = df_plot$name_partido, values = df_plot$porcentaje, type = 'pie', sort = TRUE, direction = "clockwise",
          hole = 0.6, textposition = "inside", textinfo = "percent", insidetextfont = list(color = "white"), hoverinfo = "text", text = df_plot$hovertext,
          marker = list(colors = c("#8CD2EA", "#2CBCE2", "#00A6DC", "#008BD0", "#005980", "white"), line = list(color = "77848D", width = 1)),
          rotation = 90
          )

g_congreso_mun <- ggplotly(g_congreso_mun, tooltip = c("text")) %>%
  layout(showlegend = FALSE) %>%
  config(displaylogo = FALSE, modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage")))


g_congreso_mun


cap_G_a <- df_plot$name_partido[1][[1]]
cap_G_b <- df_plot$name_partido[2][[1]]
cap_G_c <- df_plot$name_partido[3][[1]]
cap_G_d <- df_plot$name_partido[4][[1]]
cap_G_e <- df_plot$name_partido[5][[1]]
cap_G_f <- df_plot$name_partido[6][[1]]
```



