---
title: ''
params:
  id_municipio: 35003
  url.cl_area: https://datos.canarias.es/api/estadisticas/structural-resources/v1.0/codelists/ISTAC/CL_AREA_ES70_COMARCAS/01.000/codes
  url.dist_mun: https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/POBLACION
  url.viajeros_lugar: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00065A_000036/~latest.json?dim=MEDIDAS:ESTANCIA_MEDIA|VIAJEROS_ALOJADOS:TERRITORIO:ES70|ES708|35004|35010|35024|35028|35034|ES704|35003|35014|35015|35017|35030|ES705|35012|35016|35019|ES709|38001|38006|38017|38019|38023|38028|38035|38038|38040|ES706|38003|38036|38049|38050|ES707|38009|38014|38024|38027|38037|38045|ES703|38013_2007|38048|38901&lang=es
  url.tasa_ocupacion: https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/ALOJATUR_PLAZAS_OCUPACION/data?representation=MEASURE%5BABSOLUTE%5D&granularity=GEOGRAPHICAL%5BMUNICIPALITIES%5D%2CTIME%5BMONTHLY%5D
  url.ADR: https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/ALOJATUR_TARIFA_ADR/data?representation=MEASURE%5BABSOLUTE%5D&granularity=GEOGRAPHICAL%5BMUNICIPALITIES%5D%2CTIME%5BMONTHLY%5D
  url.aloj_isla: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00065A_000037/~latest.json?dim=MEDIDAS:VIAJEROS_ALOJADOS:TERRITORIO:ES70|35004|35010|35024|35028|35034|35003|35014|35015|35017|35030|35012|35016|35019|38001|38006|38017|38019|38023|38028|38035|38038|38040|38003|38036|38049|38050|38009|38014|38024|38027|38037|38045|38013_2007|38048|38901&lang=es
  url.hotel: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00065A_000001/~latest.json?dim=TERRITORIO:35004|35024|35028|35034|35003|35014|35015|35017|35030|35012|35016|35019|38001|38006|38017|38019|38023|38028|38035|38038|38040|38036|38049|38050|38009|38014|38024|38037|38013_2007|38048:MEDIDAS:ESTABLECIMIENTOS|HABITACIONES|PLAZAS:ALOJAMIENTO_TURISTICO_CATEGORIA:_T&lang=es
  url.extrahoteleros: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00065A_000002/~latest.json?dim=TERRITORIO:35010|35024|35028|35034|35003|35014|35015|35012|35016|35019|38001|38006|38017|38028|38035|38040|38003|38036|38049|38009|38014|38024|38027|38037|38045|38013_2007|38048|38901:MEDIDAS:ESTABLECIMIENTOS|HABITACIONES|PLAZAS:ALOJAMIENTO_TURISTICO_CATEGORIA:_T&lang=es
output:
  html_document:
    df_print: paged
    css: styles/FICHA.css
    self_contained: false
    lib_dir: libs
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
```

```{r librerías, include=FALSE}
list.of.packages <- c("jsonlite", "ggplot2", "knitr", "data.table", "plotly", "plyr", "dplyr", "scales", "htmlwidgets", "sf", "fuzzyjoin", "xml2", "XML", "tidyverse", "tmap", "magrittr", "reshape2", "kableExtra")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
sapply(list.of.packages, require, character.only = TRUE)
```

```{r funciones, include=FALSE}
signo <- function(value) {
  if (value > 0){sign <- "más"} else {sign <- "menos"}
  return(sign)
}

"%notin%" <- Negate("%in%")
```

```{r Municipio actual}
CL_AREA <- as_list(read_xml(params$url.cl_area))

df_CL_AREA <- tibble::as_tibble(CL_AREA) %>% 
  unnest_wider('codes') %>%
  transform(name = lapply(name, '[[', 2)) %>%
  unnest(cols = names(.)) %>%
  unnest(cols = names(.)) %>%
  readr::type_convert() %>%
  mutate(parent = gsub("^.*).", "", parent)) %>%
  select(code = id, value = name, parent)

df_CL_AREA_mun <- df_CL_AREA %>% 
  select(id = code, municipio = value, code = parent) %>%
  filter(substring(id, 0,2) != "ES") %>% 
  transform(id = if_else(substring(id, 0,5) == "38013",  "38013", id)) %>%
  filter(nchar(id) > 0 & !grepl("(", municipio, fixed = TRUE)) %>%
  left_join(df_CL_AREA, by="code") %>%
  select(id, municipio, code = parent, id_comarca = code, comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, code = parent, id_gran_comarca = code, gran_comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, code = parent, id_isla = code, isla = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, id_isla, isla, provincia = value)

municipio_actual <- df_CL_AREA_mun[df_CL_AREA_mun$id == params$id_municipio,]
```

```{r Normalización de municipios} 
recode_mun.from <- c("Oliva (La)", "Palmas de Gran Canaria (Las)", "Valsequillo", "Santa María de Guía", "Aldea de San Nicolás (La)", "Santa Lucía", "Pinar de El Hierro (El)", "Pinar de El Hierro, El", "Fuencaliente", "Llanos de Aridane (Los)", "Paso (El)", "Laguna (La)", "Rosario (El)", "Matanza de Acentejo (La)", "Sauzal (El)", "Victoria de Acentejo (La)", "Silos (Los)", "Tanque (El)", "Guancha (La)", "Orotava (La)", "Realejos (Los)", "San Miguel", "Vilaflor", "Güimar", "Icod de Los Vinos", "Puerto de La Cruz", "San Juan de La Rambla", "San Sebastián de la Gomera", "Santa Cruz de la Palma")
recode_mun.to <- c("La Oliva", "Las Palmas de Gran Canaria", "Valsequillo de Gran Canaria", "Santa María de Guía de Gran Canaria", "La Aldea de San Nicolás", "Santa Lucía de Tirajana", "El Pinar de El Hierro", "El Pinar de El Hierro", "Fuencaliente de La Palma", "Los Llanos de Aridane", "El Paso", "San Cristóbal de La Laguna", "El Rosario", "La Matanza de Acentejo", "El Sauzal", "La Victoria de Acentejo", "Los Silos", "El Tanque", "La Guancha", "La Orotava", "Los Realejos", "San Miguel de Abona", "Vilaflor de Chasna", "Güímar", "Icod de los Vinos", "Puerto de la Cruz", "San Juan de la Rambla", "San Sebastián de La Gomera", "Santa Cruz de La Palma")

recode_mun <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = recode_mun.from, to = recode_mun.to)
  df[,colname]
}
# Frontera
recode_id_Frontera <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = c("38013_1912", "38013_2007"), to = c("38013", "38013"))
  df[,colname]
}
```

```{r Municipios relacionados}
datamun <- fromJSON(params$url.dist_mun)
df_localizacion <- data.frame(mun = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["code"]],
                              nombre = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["title"]][["es"]],
                              latitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["latitude"]],
                              longitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["longitude"]]) %>% 
  filter(substring(mun, 0,2) != "ES")
df_localizacion$nombre <- recode_mun(df_localizacion, 'nombre')
df_localizacion <- filter(df_localizacion, mun != "38013_1912")
df_localizacion$mun <- recode_id_Frontera(df_localizacion, 'mun')
distancias_mun <- df_localizacion %>%
  st_as_sf(coords = c("longitud", "latitud"), crs = 4326) %>%
  st_distance

distancias_mun <- data.frame(
  mun = df_localizacion$mun,
  nombre = df_localizacion$nombre,
  distancia = distancias_mun[as.numeric(rownames(df_localizacion[df_localizacion$mun == params$id_municipio, ])),] / 1000
)

seleccion_mun <- function(df_variable, variable, p = 0.5) {
  df_dif <- df_variable %>% left_join(distancias_mun, by = "mun") 
  mun_actual <- df_dif[df_dif$mun == params$id_municipio,]
  
  df_result <- df_dif %>%
    mutate(
      dif = abs(df_dif[,variable] - mun_actual[1,variable]),
      distancia_N = scale(distancia),
      dif_N = scale(dif),
      coeficientes = p * distancia_N + (1-p) * dif_N
    ) %>%
  arrange(coeficientes)
  
  df_result[1,]
}
```


<!-- HTML -->
<body style="height: 1391px;">

<h3 style="color: #008BD0; margin: 0; text-align: right; margin: 10px;">`r municipio_actual$municipio` en cifras</h3>

```{r Mes Alojamiento}
viajeros_lugar <- fromJSON(params$url.viajeros_lugar)

mes_or_a <- levels(ordered(viajeros_lugar[["metadata"]][["temporalCoverages"]][["item"]][["id"]]))
mes_a <- data.frame(code = mes_or_a) %>%
  filter(substring(code, 5,6) == "-M") %>%
  mutate(periodo = paste0(substring(code, 0,4), substring(code, 5,8))) %>%
  transform(periodo = gsub("-M01", " Enero", periodo)) %>%
  transform(periodo = gsub("-M02", " Febrero", periodo)) %>%
  transform(periodo = gsub("-M03", " Marzo", periodo)) %>%
  transform(periodo = gsub("-M04", " Abril", periodo)) %>%
  transform(periodo = gsub("-M05", " Mayo", periodo)) %>%
  transform(periodo = gsub("-M06", " Junio", periodo)) %>%
  transform(periodo = gsub("-M07", " Julio", periodo)) %>%
  transform(periodo = gsub("-M08", " Agosto", periodo)) %>%
  transform(periodo = gsub("-M09", " Septiembre", periodo)) %>%
  transform(periodo = gsub("-M10", " Octubre", periodo)) %>%
  transform(periodo = gsub("-M11", " Noviembre", periodo)) %>%
  transform(periodo = gsub("-M12", " Diciembre", periodo)) %>%
  transform(code = gsub("M", "", code)) %>%
  transform(periodo_formatted = paste0(unlist(lapply(strsplit(periodo, " "), '[[', 2)), " ", unlist(lapply(strsplit(periodo, " "), '[[', 1))))

mes_a <- mes_a %>%
  mutate(order = as.integer(order(mes_a$code, decreasing = FALSE)))
mes_actual_a <- mes_a %>% filter(code == max(mes_a$code))
```

```{r Gráfico evolución del número de viajeros}
dV <- length(rep(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
                 each = length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                        length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]]) *
                        length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]]))) -
      length(unlist(strsplit(viajeros_lugar[["data"]][["observations"]], split = " | ", fixed = TRUE)))

df_viajeros <- data.frame(
  id_ind = rep(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
               each = length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                      length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]]) *
                      length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  mun = rep(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]]) *
                   length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  code = rep(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
             each = length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  id_lugar = rep(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]],
                 times = length(viajeros_lugar[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]])),
  valor = c(unlist(strsplit(viajeros_lugar[["data"]][["observations"]], split = " | ", fixed = TRUE)), rep(NA, dV)))

df_lugar <- data.frame(
  id_lugar = viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[5]][["id"]],
  lugar = vector(mode = "character", length = viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][5]))

for(i in 1:nrow(df_lugar)) {
  df_lugar$lugar[i] <- viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[5]][["name"]][["text"]][[i]][["value"]]
}

df_viajeros <- df_viajeros %>%
  filter(substring(code, 5,6) == "-M") %>%
  right_join(df_lugar, by = "id_lugar") %>%
  transform(code = gsub("M", "", code)) %>%
  select(!id_lugar)
df_viajeros$valor <- df_viajeros$valor %>% as.numeric
df_viajeros$mun <- recode_id_Frontera(df_viajeros, 'mun')

num_Canarias_total <- df_viajeros %>% filter(id_ind == "VIAJEROS_ALOJADOS" & mun == "ES70" & code == mes_actual_a$code & lugar == "Total") %>% select(valor) %>% as.numeric

df_viajeros <- df_viajeros[with(df_viajeros, order(code)), ]
df_u <- df_viajeros %>%
  filter(id_ind == "VIAJEROS_ALOJADOS" & substring(mun, 0,2) != "ES" & lugar == "Total") %>%
  select(mun, code, valor) %>%
  arrange(code)

related_mun <- df_u %>% filter(code == mes_actual_a$code)
related_mun <- seleccion_mun(related_mun %>% select(mun, valor), 'valor')

df_a <- related_mun %>%
  select(mun, nombre) %>%
  left_join(df_u, by = "mun") %>%
  select(id = mun, code, nombre, valor) %>%
  left_join(df_CL_AREA_mun, by = "id") %>%
  select(id, code = code, nombre, valor) %>%
  left_join(mes_a, by = "code") %>%
  transform(tasa = ifelse(substring(code, 0,4) != min(substring(code, 0,4)), round(100*((valor / lag(valor, n = 12)) - 1), 1), NA)) %>%
  filter(order < mes_actual_a$order+1)

ano_min <- min(as.integer(substring(df_a$code, 0,4)))
ano_max <- max(as.integer(substring(df_a$code, 0,4)))

line_range_min <- max(1, nrow(df_a[df_a$nombre == municipio_actual$municipio, ]) - 5*12)
line_range_max <- nrow(df_a[df_a$nombre == municipio_actual$municipio, ])
I_Aloj_num <- df_a %>% filter(order == line_range_min) %>% select(valor) %>% as.numeric
I_Aloj <- I_Aloj_num %>% format(big.mark = ".", decimal.mark = ",")
Num_Aloj_num <- df_a %>% filter(code == mes_actual_a$code) %>% select(valor) %>% as.numeric
Num_Aloj <- Num_Aloj_num %>% format(big.mark = ".", decimal.mark = ",")

df_a <- df_a %>%
  transform(hovertext = paste0(
    "<b>", nombre, "</b><br>Personas alojadas: ", ifelse(is.na(valor), " -", trimws(format(valor, big.mark = ".", decimal.mark = ","))),
    "<br>Tasa de variación: ", ifelse(is.na(tasa), " -", paste0(trimws(format(round(tasa, 1), big.mark = ".", decimal.mark = ",")), "%"))))

g_line_colours <- setNames(c('rgba(0, 89, 128, 0.8)', 'rgba(0, 139, 208, 0.8)', 'rgba(140, 210, 234, 0.8)' ), related_mun$nombre)

g_line_a <- ggplot(data = df_a, aes(x = code, y = valor, group = nombre, colour = nombre, text = hovertext)) +
  geom_line(size = 0.7) +
  geom_text(aes(x = line_range_min, y = (0.92*I_Aloj_num), label = I_Aloj, colour = '#000000'), size = 3.5, nudge_x = 2) +
  geom_text(aes(x = line_range_max, y = (0.94*Num_Aloj_num), label = Num_Aloj, colour = '#000000'), size = 3.5, nudge_x = -2) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none") +
  scale_colour_manual(values = g_line_colours) +
  scale_size_manual(values = c(1, 0.1, 0.1)) +
  scale_x_discrete(breaks = function(x){paste0(ano_min:ano_max, "-01")}, labels = function(x){substr(x, 0,4)}) +
  scale_y_continuous(labels = function(x){paste0(format(x/10^3, big.mark = ".", decimal.mark = ","), " mil")}, n.breaks = 5, limits = c(0, NA))

g_line_a <- ggplotly(g_line_a, tooltip = "text") %>%
  config(displaylogo = FALSE, modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>%
  layout(hoverlabel = "", hovermode = 'x unified',
         xaxis = list(autorange = FALSE,
                      range = c(line_range_min, line_range_max))) %>%
  style(hoverinfo = "skip", traces = c(2, 3))
```

```{r Indicador Tasa de Ocupación}
tasa_ocupacion <- fromJSON(params$url.tasa_ocupacion)

df_tasa_ocupacion <- data.frame(
  mun = rep(names(tasa_ocupacion[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["index"]]),
            each=length(tasa_ocupacion[["dimension"]][["TIME"]][["representation"]][["index"]])),
  code = rep(names(tasa_ocupacion[["dimension"]][["TIME"]][["representation"]][["index"]]),
            times=length(tasa_ocupacion[["dimension"]][["MEASURE"]][["representation"]][["index"]])),
  valor = tasa_ocupacion[["observation"]])
df_tasa_ocupacion$valor <- df_tasa_ocupacion$valor %>% as.numeric %>% round(1)
df_tasa_ocupacion$mun <- recode_id_Frontera(df_tasa_ocupacion, 'mun')
```

```{r Indicador ADR}
ADR <- fromJSON(params$url.ADR)

df_ADR <- data.frame(
  mun = rep(names(ADR[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["index"]]),
            each=length(ADR[["dimension"]][["TIME"]][["representation"]][["index"]])),
  code = rep(names(ADR[["dimension"]][["TIME"]][["representation"]][["index"]]),
            times=length(ADR[["dimension"]][["MEASURE"]][["representation"]][["index"]])),
  valor = ADR[["observation"]])
df_ADR$valor <- df_ADR$valor %>% as.numeric %>% round(1)
df_ADR$mun <- recode_id_Frontera(df_ADR, 'mun')
```

```{r Barras Lugar}
df_viajeros_lugar <- df_viajeros %>%
  filter(id_ind == "VIAJEROS_ALOJADOS" & code == mes_actual_a$code & lugar %notin% c("Total", "Mundo (excluida España)")) %>%
  select(mun, lugar, valor)

df_viajeros_lugar <- df_viajeros_lugar %>%
  transform(lugar = gsub("Otros(.)+", "Otros países", lugar))
df_viajeros_lugar_mun <- df_viajeros_lugar %>% filter(mun == params$id_municipio)

df_viajeros_lugar_C <- df_viajeros_lugar %>%
  filter(mun == "ES70") %>%
  select(lugar, valor)
df_viajeros_lugar_mun <- df_viajeros_lugar_mun %>%
  mutate(porcentaje = if_else(is.na(valor), 0, df_viajeros_lugar_mun$valor / Num_Aloj_num * 100),
         valor_Canarias = df_viajeros_lugar_C$valor,
         porcentaje_Canarias = df_viajeros_lugar_C$valor / num_Canarias_total * 100) %>%
  transform(valor = if_else(is.na(valor), 0, valor))

df_viajeros_lugar_plot <- df_viajeros_lugar_mun %>%
  mutate(label = "|") %>%
  arrange(valor_Canarias) %>%
  arrange(valor)
df_viajeros_lugar_plot$lugar <- ordered(df_viajeros_lugar_plot$lugar, levels = df_viajeros_lugar_plot$lugar)

df_viajeros_lugar_plot <- df_viajeros_lugar_plot %>%
  transform(hovertext = paste0(
    "<b>", trimws(lugar), "</b><br>",
    trimws(format(valor, big.mark = ".", decimal.mark = ",")), 
    " (", trimws(format(round(porcentaje, 1), big.mark = ".", decimal.mark = ",")), "%)<br>",
    "Canarias: ", trimws(format(valor_Canarias, big.mark = ".", decimal.mark = ",")),
    " (", trimws(format(round(porcentaje_Canarias, 1), big.mark = ".", decimal.mark = ",")), "%)"
    ))

df_viajeros_lugar_0 <- df_viajeros_lugar_plot %>%
  transform(porcentaje = 0,
            porcentaje_Canarias = 0,
            label = "")

df_viajeros_lugar_plot <- rbind(df_viajeros_lugar_plot, df_viajeros_lugar_0)

col <- c("#D5EDFA", "#8CD2EA", "#2CBCE2", "#00A6DC", "#0099CC", "#008BD0", "#0072A2", "#005980", "#00405B")

g_viajeros_lugar <- ggplot(df_viajeros_lugar_plot, aes(y = lugar, fill = lugar, label = label, name = NULL, text = hovertext)) +
  geom_bar(stat = "identity", alpha = 0.8, width = 0.6, aes(x = porcentaje)) +
  geom_text(size = 7, color = "#59656E", aes(x = porcentaje_Canarias, text = "")) +
  scale_fill_manual(values = col) +
  theme_minimal() +
  guides(fill = guide_legend(title = " ")) +
  labs(title = "", x = NULL, y = NULL, colour = " ") +
  theme(axis.text.x = element_text(),
        axis.line = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(colour = "lightgray"),
        panel.grid.minor.x = element_line(colour = "lightgray"),
        panel.background = element_rect(fill = "white"),
        legend.position = "none") +
  scale_x_continuous(labels = function(x){paste0(format(x, big.mark = '.', decimal.mark = ","), '%')})

g_viajeros_lugar <- ggplotly(g_viajeros_lugar, tooltip = c("text")) %>%
  layout(hoverlabel = "", hovermode = 'y unified', margin = list(l = 0, r = 0)) %>%
  config(displaylogo = FALSE, modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>%
  style(hoverinfo = "skip", traces = c(10:19))
```

```{r Barras Islas}
aloj_isla <- fromJSON(params$url.aloj_isla)

dA <- length(rep(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
                 each = length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[4]][["code"]]) *
                        length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]]))) -
      length(unlist(strsplit(aloj_isla[["data"]][["observations"]], split = " | ", fixed = TRUE)))

df_aloj_isla <- data.frame(
  mun = rep(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
            each = length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[4]][["code"]]) *
                   length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  code = rep(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[4]][["code"]],
                each = length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  id_lugar = rep(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]],
                 times = length(aloj_isla[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  valor = c(unlist(strsplit(aloj_isla[["data"]][["observations"]], split = " | ", fixed = TRUE)), rep(NA, dA)))

df_lugar <- data.frame(
  id_lugar = aloj_isla[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[5]][["id"]],
  lugar = vector(mode = "character", length = aloj_isla[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][5]))

for(i in 1:nrow(df_lugar)) {
  df_lugar$lugar[i] <- aloj_isla[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[5]][["name"]][["text"]][[i]][["value"]]
}

df_aloj_isla <- df_aloj_isla %>%
  filter(substring(code, 5,6) == "-M") %>%
  right_join(df_lugar, by = "id_lugar") %>%
  transform(code = gsub("M", "", code)) %>%
  select(!id_lugar)
df_aloj_isla$valor <- df_aloj_isla$valor %>% as.numeric
df_aloj_isla$mun <- recode_id_Frontera(df_aloj_isla, 'mun')

num_viajeros_canarios_mun <- df_aloj_isla %>%
  filter(mun == params$id_municipio & code == mes_actual_a$code & lugar == "Canarias") %>%
  transform(valor = if_else(is.na(valor), 0, valor)) %>%
  select(valor) %>% as.numeric
num_viajeros_canarios_C <- df_aloj_isla %>%
  filter(mun == "ES70" & code == mes_actual_a$code & lugar == "Canarias") %>% select(valor) %>% as.numeric

df_aloj_isla_mun <- df_aloj_isla %>%
  filter(mun == params$id_municipio & code == mes_actual_a$code & lugar %notin% c("España (excluida Canarias)", "Canarias")) %>%
  select(lugar, valor)
df_aloj_isla_C <- df_aloj_isla %>%
  filter(mun == "ES70" & code == mes_actual_a$code & lugar %notin% c("España (excluida Canarias)", "Canarias")) %>%
  select(lugar, valor)
df_aloj_isla_mun <- df_aloj_isla_mun %>%
  mutate(porcentaje = if_else(is.na(valor), 0, df_aloj_isla_mun$valor / num_viajeros_canarios_mun * 100),
         valor_Canarias = df_aloj_isla_C$valor,
         porcentaje_Canarias = df_aloj_isla_C$valor / num_viajeros_canarios_C * 100) %>%
  transform(valor = if_else(is.na(valor), 0, valor))

df_aloj_isla_plot <- df_aloj_isla_mun %>%
  mutate(label = "|") %>%
  arrange(valor_Canarias) %>%
  arrange(valor)
df_aloj_isla_plot$lugar <- ordered(df_aloj_isla_plot$lugar, levels = df_aloj_isla_plot$lugar)

df_aloj_isla_plot <- df_aloj_isla_plot %>%
  transform(hovertext = paste0(
    "<b>", trimws(lugar), "</b><br>",
    trimws(format(valor, big.mark = ".", decimal.mark = ",")),
    " (", trimws(format(round(porcentaje, 1), big.mark = ".", decimal.mark = ",")), "%)<br>",
    "Canarias: ", trimws(format(valor_Canarias, big.mark = ".", decimal.mark = ",")),
    " (", trimws(format(round(porcentaje_Canarias, 1), big.mark = ".", decimal.mark = ",")), "%)"
  ))

df_aloj_isla_0 <- df_aloj_isla_plot %>%
  transform(porcentaje = 0,
            porcentaje_Canarias = 0,
            label = "")

df_aloj_isla_plot <- rbind(df_aloj_isla_plot, df_aloj_isla_0)

g_aloj_isla <- ggplot(data = df_aloj_isla_plot, aes(y = lugar, fill = lugar, label = label, name = NULL, text = hovertext)) +
  geom_bar(stat = "identity", alpha = 0.8, width = 0.6, aes(x = porcentaje)) +
  geom_text(size = 7, color = "#59656E", aes(x = porcentaje_Canarias, text = "")) +
  theme_minimal() +
  labs(title = "", x = NULL, y = NULL, colour = " ") +
  guides(fill = FALSE) +
  scale_fill_manual(values = c("#D5EDFA", "#8CD2EA", "#2CBCE2", "#00A6DC", "#008BD0", "#0072A2", "#005980")) +
  theme(axis.text.x = element_text(),
        axis.line = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(colour = "lightgray"),
        panel.grid.minor.x = element_line(colour = "lightgray"),
        panel.background = element_rect(fill = "white"),
        legend.position = "none") +
  scale_x_continuous(labels = function(x){paste0(format(x, big.mark = '.', decimal.mark = ","), '%')})

g_aloj_isla <- ggplotly(g_aloj_isla, tooltip = c("text")) %>%
  layout(hovermode = 'y unified', margin = list(l = 0, r = 0)) %>%
  config(displaylogo = FALSE,  modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>%
  style(hoverinfo = "skip", traces = c(8:14))
```

```{r Tipos de alojamiento}
hoteles <- fromJSON(params$url.hotel)

df_hoteles <- data.frame(
  code = rep(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
                each = length(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                       length(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  mun = rep(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  id_ind = rep(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
            times = length(hoteles[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]])),
  valor = unlist(strsplit(hoteles[["data"]][["observations"]], split = " | ", fixed = TRUE)))

df_ind <- data.frame(
  id_ind = hoteles[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["id"]],
  ind = vector(mode = "character", length = hoteles[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][3]))

for(i in 1:nrow(df_ind)) {
  df_ind$ind[i] <- hoteles[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[3]][["name"]][["text"]][[i]][["value"]]
}

df_hoteles <- df_hoteles %>%
  filter(substring(code, 5,6) == "-M") %>%
  transform(code = gsub("M", "", code))
df_hoteles$valor <- df_hoteles$valor %>% as.numeric
df_hoteles$mun <- recode_id_Frontera(df_hoteles, 'mun')

extrahoteleros <- fromJSON(params$url.extrahoteleros)

df_extrahoteleros <- data.frame(
  code = rep(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
                each = length(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                       length(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  mun = rep(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  id_ind = rep(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
            times = length(extrahoteleros[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]])),
  valor = unlist(strsplit(extrahoteleros[["data"]][["observations"]], split = " | ", fixed = TRUE)))

df_extrahoteleros <- df_extrahoteleros %>%
  filter(substring(code, 5,6) == "-M") %>%
  transform(code = gsub("M", "", code))
df_extrahoteleros$valor <- df_extrahoteleros$valor %>% as.numeric
df_extrahoteleros$mun <- recode_id_Frontera(df_extrahoteleros, 'mun')
```

<h1 style="color: #005980; margin: 15px;">Hostelería y turismo</h1>

```{r Alojamiento, results='asis'}
df_medida <- data.frame(
  id_ind = c(viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[1]][["id"]][3],
             viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[1]][["id"]][1],
             "tasa_oc", "adr", "ESTABLECIMIENTOS_H", "PLAZAS_H", "HABITACIONES_H", "ESTABLECIMIENTOS_A", "PLAZAS_A", "HABITACIONES_A"),
  ind = c("Personas alojadas", viajeros_lugar[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[1]][["name"]][["text"]][[1]][["value"]],
          "Tasa de ocupación", "Tarifa media diaria", "Hoteles", "Plazas ", "Habitaciones", "Apartamentos", "Plazas", "Apartamentos "))

df_medida$id_ind <- factor(df_medida$id_ind, levels = df_medida$id_ind)
df_medida$ind <- factor(df_medida$ind, levels = df_medida$ind)

tb_periodos <- df_a %>%
  filter(order > max(df_a$order) - 8) %>%
  select(code)

df_aloj <- df_viajeros %>%
  filter(mun == params$id_municipio & id_ind == "VIAJEROS_ALOJADOS" & code %in% tb_periodos$code & lugar == "Total") %>%
  mutate(valor = ifelse(is.na(valor), " -", format(as.integer(valor), big.mark = ".", decimal.mark = ","))) %>%
  select(id_ind, code, valor)

df_estancia_media <- df_viajeros %>%
  filter(mun == params$id_municipio & id_ind == "ESTANCIA_MEDIA" & code %in% tb_periodos$code & lugar == "Total") %>%
  mutate(valor = ifelse(is.na(valor), " -", format(round(valor, 1), big.mark = ".", decimal.mark = ",", nsmall = 1))) %>%
  select(id_ind, code, valor)

df_tasa_ocupacion <- df_tasa_ocupacion %>%
  filter(mun == params$id_municipio & code %in% tb_periodos$code) %>%
  mutate(id_ind = c('tasa_oc'),
         valor = ifelse(is.na(valor), " -", paste0(format(valor, big.mark = ".", decimal.mark = ",", nsmall = 1), "%"))) %>%
  select(id_ind, code, valor)
df_ADR <- df_ADR %>%
  filter(mun == params$id_municipio & code %in% tb_periodos$code) %>%
  mutate(id_ind = c('adr'),
         valor = ifelse(is.na(valor), " -", format(valor, big.mark = ".", decimal.mark = ",", nsmall = 1))) %>%
  select(id_ind, code, valor)

df_hoteles_mun <- df_hoteles %>%
  filter(mun == params$id_municipio & code %in% tb_periodos$code) %>%
  mutate(id_ind = recode(id_ind, "ESTABLECIMIENTOS" = "ESTABLECIMIENTOS_H"),
         id_ind = recode(id_ind, "PLAZAS" = "PLAZAS_H"),
         id_ind = recode(id_ind, "HABITACIONES" = "HABITACIONES_H"),
         valor = ifelse(is.na(valor), " -", paste0(format(round(valor, 0), big.mark = ".", decimal.mark = ",")))) %>%
  select(!mun)
df_extrahoteleros_mun <- df_extrahoteleros %>%
  filter(mun == params$id_municipio & code %in% tb_periodos$code) %>%
  mutate(id_ind = recode(id_ind, "ESTABLECIMIENTOS" = "ESTABLECIMIENTOS_A"),
         id_ind = recode(id_ind, "PLAZAS" = "PLAZAS_A"),
         id_ind = recode(id_ind, "HABITACIONES" = "HABITACIONES_A"),
         valor = ifelse(is.na(valor), " -", paste0(format(round(valor, 0), big.mark = ".", decimal.mark = ",")))) %>%
  select(!mun)

tb_aloj <- df_aloj %>%
  rbind(df_estancia_media) %>%
  rbind(df_tasa_ocupacion) %>%
  rbind(df_ADR) %>%
  rbind(df_hoteles_mun) %>%
  rbind(df_extrahoteleros_mun) %>%
  left_join(df_medida, by = "id_ind") %>%
  acast(ind ~ code, value.var = 'valor')

tb_a <- tb_aloj %>%
  kable(format = 'html', align = 'c', table.attr = "class=\"my-table-2\"") %>%
  kable_styling(full_width = TRUE, position = "left") %>%
  column_spec(2:5, width = "23%")
```
<div class="highlight" style="width: 100% !important; margin: 15px 5px;">
<h2 style="color: #005980; margin-left: 20px;">Alojamientos turísticos</h2>

<div class="row" style="padding: 20px 5px 0;">`r g_line_a`</div>

<div class="row" style="padding: 20px 5px 0;">`r tb_a`</div>


<div class="row">
  <div class="column-2" style="height: 290px;">`r g_viajeros_lugar`</div>

  <div class="column-2" style="height: 290px;">`r g_aloj_isla`</div>
</div>

<div class="row">
<div class="progressbar-legend-container" style="margin-top:10px;">
<div class='progressbar-legend'>
  <div class='progress-bar-C-a'>|</div><div class='sp-content-b'>Canarias</div></div>
</div>
</div>
</div>

