---
title: ''
params:
  id_municipio: 35003
  url.cl_area: https://datos.canarias.es/api/estadisticas/structural-resources/v1.0/codelists/ISTAC/CL_AREA_ES70_COMARCAS/01.000/codes
  url.dist_mun: https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/POBLACION
  url.nacionalidad: http://www.gobiernodecanarias.org/istac/jaxi-istac/tabla.do?accion=jsonMtd&uuidConsulta=ddea361b-df10-41c1-ad96-3ac1de7e9958
  url.participacion: https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/C00010A_000001/~latest.json?dim=TERRITORIO:35004|35010|35018|35024|35028|35029|35034|35003|35007|35014|35015|35017|35030|35001|35002|35005|35006|35008|35009|35011|35012|35013|35016|35019|35020|35021|35022|35023|35025|35026|35027|35031|35032|35033|38001|38004|38005|38006|38010|38011|38012|38015|38017|38018|38019|38020|38022|38023|38025|38026|38028|38031|38032|38034|38035|38038|38039|38040|38041|38042|38043|38044|38046|38051|38052|38002|38003|38021|38036|38049|38050|38007|38008|38009|38014|38016|38024|38027|38029|38030|38033|38037|38045|38047|38053|38013_1912|38013_2007|38048|38901&lang=es
output:
  html_document:
    df_print: paged
    css: styles/FICHA.css
    # self_contained: false
    # lib_dir: libs
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
```

```{r librerías, include=FALSE}
list.of.packages <- c("jsonlite", "ggplot2", "knitr", "data.table", "plotly", "plyr", "dplyr", "scales", "htmlwidgets", "sf", "fuzzyjoin", "xml2", "XML", "tidyverse", "tmap", "magrittr", "reshape2", "kableExtra")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
sapply(list.of.packages, require, character.only = TRUE)
```

```{r funciones, include=FALSE}
signo <- function(value) {
  if (value > 0){sign <- "más"} else {sign <- "menos"}
  return(sign)
}

"%notin%" <- Negate("%in%")

get_nombre_partido <- function(nombre) {
  string_list <- str_split(nombre, pattern = " ")[[1]]
  result <- ""
  line.char <- 0
  for(word.index in 1:length(string_list)) {
    if((line.char + nchar(string_list[word.index])) < 38) {
      result <- paste0(result, " ", string_list[word.index])
      line.char <- line.char + 1 + nchar(string_list[word.index])
    } else {
      result <- paste0(result, "<br>", string_list[word.index])
      line.char <- nchar(string_list[word.index])
    }
  }
  trimws(result)
}
```

```{r Municipio actual}
CL_AREA <- as_list(read_xml(params$url.cl_area))

df_CL_AREA <- tibble::as_tibble(CL_AREA) %>% 
  unnest_wider('codes') %>%
  transform(name = lapply(name, '[[', 2)) %>%
  unnest(cols = names(.)) %>%
  unnest(cols = names(.)) %>%
  readr::type_convert() %>%
  mutate(parent = gsub("^.*).", "", parent)) %>%
  select(code = id, value = name, parent)

df_CL_AREA_mun <- df_CL_AREA %>% 
  select(id = code, municipio = value, code = parent) %>%
  filter(substring(id, 0,2) != "ES") %>% 
  transform(id = if_else(substring(id, 0,5) == "38013",  "38013", id)) %>%
  filter(nchar(id) > 0 & !grepl("(", municipio, fixed = TRUE)) %>%
  left_join(df_CL_AREA, by="code") %>%
  select(id, municipio, code = parent, id_comarca = code, comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, code = parent, id_gran_comarca = code, gran_comarca = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, code = parent, id_isla = code, isla = value) %>% 
  left_join(df_CL_AREA, by="code") %>% 
  select(id, municipio, id_comarca, comarca, id_gran_comarca, gran_comarca, id_isla, isla, provincia = value)

municipio_actual <- df_CL_AREA_mun[df_CL_AREA_mun$id == params$id_municipio,]
```

```{r Normalización de municipios} 
recode_mun.from <- c("Oliva (La)", "Palmas de Gran Canaria (Las)", "Valsequillo", "Santa María de Guía", "Aldea de San Nicolás (La)", "Santa Lucía", "Pinar de El Hierro (El)", "Pinar de El Hierro, El", "Fuencaliente", "Llanos de Aridane (Los)", "Paso (El)", "Laguna (La)", "Rosario (El)", "Matanza de Acentejo (La)", "Sauzal (El)", "Victoria de Acentejo (La)", "Silos (Los)", "Tanque (El)", "Guancha (La)", "Orotava (La)", "Realejos (Los)", "San Miguel", "Vilaflor", "Güimar", "Icod de Los Vinos", "Puerto de La Cruz", "San Juan de La Rambla", "San Sebastián de la Gomera", "Santa Cruz de la Palma")
recode_mun.to <- c("La Oliva", "Las Palmas de Gran Canaria", "Valsequillo de Gran Canaria", "Santa María de Guía de Gran Canaria", "La Aldea de San Nicolás", "Santa Lucía de Tirajana", "El Pinar de El Hierro", "El Pinar de El Hierro", "Fuencaliente de La Palma", "Los Llanos de Aridane", "El Paso", "San Cristóbal de La Laguna", "El Rosario", "La Matanza de Acentejo", "El Sauzal", "La Victoria de Acentejo", "Los Silos", "El Tanque", "La Guancha", "La Orotava", "Los Realejos", "San Miguel de Abona", "Vilaflor de Chasna", "Güímar", "Icod de los Vinos", "Puerto de la Cruz", "San Juan de la Rambla", "San Sebastián de La Gomera", "Santa Cruz de La Palma")

recode_mun <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = recode_mun.from, to = recode_mun.to)
  df[,colname]
}
# Frontera
recode_Frontera <- function(df) {
  df_f <- rbind(df %>% filter(ano %in% c(2008:max(ano)) & mun == "38013_1912"),
                df %>% filter(ano %in% c(2000:2007) & mun == "38013_2007"))
  df <- df %>% anti_join(df_f)
}

recode_id_Frontera <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = c("38013_1912", "38013_2007"), to = c("38013", "38013"))
  df[,colname]
}
recode_Frontera_electorales <- function(df) {
  df_f <- rbind(df %>% filter(proceso != "AUTONOMICAS_2007" & mun == "38013_1912"),
                df %>% filter(proceso == "AUTONOMICAS_2007" & mun == "38013_2007"),
                df %>% filter(proceso != "MUNICIPALES_2007" & mun == "38013_1912"),
                df %>% filter(proceso == "MUNICIPALES_2007" & mun == "38013_2007"),
                df %>% filter(proceso != "CABILDO_2007" & mun == "38013_1912"),
                df %>% filter(proceso == "CABILDO_2007" & mun == "38013_2007"),
                df %>% filter(proceso %notin% c("CONGRESO_2004", "CONGRESO_2000") & mun == "38013_1912"),
                df %>% filter(proceso %in% c("CONGRESO_2004", "CONGRESO_2000") & mun == "38013_2007"),
                df %>% filter(proceso != "PARLAMENTO_EUROPEO_2004" & mun == "38013_1912"),
                df %>% filter(proceso == "PARLAMENTO_EUROPEO_2004" & mun == "38013_2007"),
                df %>% filter(proceso %notin% c("SENADO_2004", "SENADO_2000") & mun == "38013_1912"),
                df %>% filter(proceso %in% c("SENADO_2004", "SENADO_2000") & mun == "38013_2007"))
  df <- df %>% anti_join(df_f)
}
```

```{r Municipios relacionados}
datamun <- fromJSON(params$url.dist_mun)
df_localizacion <- data.frame(mun = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["code"]],
                              nombre = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["title"]][["es"]],
                              latitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["latitude"]],
                              longitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["longitude"]]) %>% 
  filter(substring(mun, 0,2) != "ES")
df_localizacion$nombre <- recode_mun(df_localizacion, 'nombre')
df_localizacion <- filter(df_localizacion, mun != "38013_1912")
df_localizacion$mun <- recode_id_Frontera(df_localizacion, 'mun')
distancias_mun <- df_localizacion %>%
  st_as_sf(coords = c("longitud", "latitud"), crs = 4326) %>%
  st_distance

distancias_mun <- data.frame(
  mun = df_localizacion$mun,
  nombre = df_localizacion$nombre,
  distancia = distancias_mun[as.numeric(rownames(df_localizacion[df_localizacion$mun == params$id_municipio, ])),] / 1000
)

seleccion_mun <- function(df_variable, variable, p = 0.5) {
  df_dif <- df_variable %>% left_join(distancias_mun, by = "mun") 
  mun_actual <- df_dif[df_dif$mun == params$id_municipio,]
  
  df_result <- df_dif %>%
    mutate(
      dif = abs(df_dif[,variable] - mun_actual[1,variable]),
      distancia_N = scale(distancia),
      dif_N = scale(dif),
      coeficientes = p * distancia_N + (1-p) * dif_N
    ) %>%
  arrange(coeficientes)
  
  df_result[1,]
}
```

```{r Población según sexos y nacionalidades}
data_nacionalidad <- fromJSON(params$url.nacionalidad)
df_nacionalidad <- cbind(data.frame(do.call('rbind', data_nacionalidad[["data"]][["dimCodes"]])), data_nacionalidad[["data"]][["Valor"]])
colnames(df_nacionalidad) <- c('mun', 'nacionalidad', 'ano', 'sexo', 'valor')
df_nacionalidad$mun <- factor(df_nacionalidad$mun, levels=data_nacionalidad[["categories"]][["codes"]][[1]], labels=data_nacionalidad[["categories"]][["labels"]][[1]])
df_nacionalidad$nacionalidad <- factor(df_nacionalidad$nacionalidad, levels=data_nacionalidad[["categories"]][["codes"]][[2]], labels=data_nacionalidad[["categories"]][["labels"]][[2]])
df_nacionalidad$ano <- as.numeric(df_nacionalidad$ano)
df_nacionalidad$sexo <- factor(df_nacionalidad$sexo, levels=data_nacionalidad[["categories"]][["codes"]][[4]], labels=data_nacionalidad[["categories"]][["labels"]][[4]])
df_nacionalidad$valor <- as.numeric(df_nacionalidad$valor)
df_nacionalidad$mun <- recode_mun(df_nacionalidad, 'mun')
df_nacionalidad <- df_nacionalidad %>% 
  mutate(nacionalidad = trimws(nacionalidad))
```

```{r Barras nacionalidades}
max_ano <- max(df_nacionalidad$ano)
Num_Pobl_num <- df_nacionalidad %>% filter(mun == municipio_actual$municipio & nacionalidad == "TOTAL" & ano == max_ano & sexo == "AMBOS SEXOS") %>% select(valor) %>% as.numeric
ranking_nacionalidad_mun <- df_nacionalidad %>%
  filter(mun == municipio_actual$municipio &
         nacionalidad %notin% c("TOTAL", "ESPAÑA", "EXTRANJERO", "UNIÓN EUROPEA (27_2020)", "Ampliación de 2004", "Otros países de la Unión Europea", "PAÍSES EUROPEOS NO UE (27_2020)",
                                "Otros países de Europa", "ÁFRICA", "Otros de África", "AMÉRICA", "Otros países de América", "ASIA", "Otros países de Asia", "OCEANÍA") &
         ano == max_ano & sexo == "AMBOS SEXOS") %>%
  select(nacionalidad, valor) %>%
  top_n(10, valor) %>%
  arrange(-valor)

if(length(ranking_nacionalidad_mun$nacionalidad) > 10){
  ranking_nacionalidad_mun <- ranking_nacionalidad_mun %>% filter(valor != min(ranking_nacionalidad_mun$valor))
}

Num_total_extr <- df_nacionalidad %>% 
  filter(mun == municipio_actual$municipio & nacionalidad == "EXTRANJERO" & ano == max_ano & sexo == "AMBOS SEXOS") %>% select(valor) %>% as.numeric

df_nacionalidad_mun_sexo <- df_nacionalidad %>%
  filter(mun == municipio_actual$municipio & nacionalidad %in% ranking_nacionalidad_mun$nacionalidad & ano == max_ano & sexo !="AMBOS SEXOS") %>% 
  arrange(valor)
df_nacionalidad_mun_sexo <- cbind(df_nacionalidad_mun_sexo, porcentaje = df_nacionalidad_mun_sexo$valor / Num_total_extr) %>% 
  transform(valor = if_else(sexo == "Hombres", -valor, valor))
ranking_nacionalidad_mun_o <- ranking_nacionalidad_mun %>% arrange(valor)
df_nacionalidad_mun_sexo$nacionalidad <- ordered(df_nacionalidad_mun_sexo$nacionalidad, levels = ranking_nacionalidad_mun_o$nacionalidad)

df_nacionalidad_mun_sexo <- df_nacionalidad_mun_sexo %>%
  transform(hovertext = paste0(
    ifelse(sexo == "Hombres", paste0("<b>", trimws(nacionalidad),"</b>"), ""),
    "<br><b>", sexo, "</b><br>",
    trimws(format(abs(valor), big.mark = ".", decimal.mark = ",")),
    " (", trimws(format(round(abs(porcentaje)*100, 1), big.mark = ".", decimal.mark = ",")), "%)"))

g_nacionalidad_mun_sexo <- ggplot(df_nacionalidad_mun_sexo, aes(y = valor, x = nacionalidad, fill = sexo, group = sexo, text = hovertext)) +
  geom_bar(stat = "identity", alpha = 0.8, position = position_stack(reverse = TRUE)) +
  coord_flip() +
  theme_minimal() +
  guides(fill = guide_legend(title = " ")) +
  labs(x = NULL, y = NULL, colour = " ") +
  scale_fill_manual(values = c("Mujeres" = "#8CD2EA", "Hombres" = "#005980")) +
  theme(axis.line = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(colour = "lightgray"),
        panel.grid.minor.x = element_line(colour = "lightgray"),
        panel.background = element_rect(fill = "white"),
        legend.position = "none") +
  scale_y_continuous(labels = function(x){format(abs(x), big.mark = '.', decimal.mark = ",")},
                     limits = c(-1, 1)*max(abs(df_nacionalidad_mun_sexo$valor)),
                     n.breaks = 5)

g_nacionalidad_mun_sexo <- ggplotly(g_nacionalidad_mun_sexo, tooltip = c("text")) %>%
  layout(hoverlabel = "", margin = list(t = 10), hovermode = 'y unified') %>%
  config(displaylogo = FALSE,  modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>% 
  style(hoverinfo = "skip", traces = c(3, 4))
```


<!-- HTML -->
<body style="height: 1391px;">

<h3 style="color: #008BD0; margin: 0; text-align: right; margin: 10px;">`r municipio_actual$municipio` en cifras</h3>

```{r Nacionalidades, results='asis'}
tb_nacionalidad <- df_nacionalidad %>%
  filter(mun == municipio_actual$municipio &
         nacionalidad %in% c("ESPAÑA", "EXTRANJERO", ranking_nacionalidad_mun$nacionalidad) &
         ano == max_ano &
         sexo == "AMBOS SEXOS") %>%
  arrange(-valor) %>%
  top_n(8) %>%
  transform(nacionalidad = ifelse(nacionalidad == "ESPAÑA", "España", nacionalidad)) %>%
  transform(nacionalidad = ifelse(nacionalidad == "EXTRANJERO", "Extranjero", nacionalidad)) %>%
  transform(Habitantes = paste0(format(valor, big.mark = ".", decimal.mark = ",")),
            Porcentaje = paste0(format(round((valor / Num_Pobl_num * 100), 1), big.mark = ".", decimal.mark = ",", nsmall = 1), "%")) %>%
  select(" " = nacionalidad, Habitantes, Porcentaje)

tb_nacionalidad <- tb_nacionalidad %>%
  kable(format = 'html', align = 'l', table.attr = "class=\"my-table-2\"") %>%
  kable_styling(full_width = TRUE, position = 'left') %>%
  add_indent(c(3:8)) %>%
  column_spec(1, width = '40%') %>%
  column_spec(2:3, width = '30%')
```
<div class="highlight" style="width: 100% !important; margin: 15px 5px;">
<h2 style="color: #005980; margin-left: 20px;">Nacionalidades</h2>

<div class="row">
  <div class="column-2" style="margin-top: 6px;">`r tb_nacionalidad`</div>

  <div class="column-2" style="height: 300px;">`r g_nacionalidad_mun_sexo`</div>
</div>

<div class="row">
  <div class="column-2"></div>
  <div class="column-2">
<div class="progressbar-legend-container">
  <div class='progressbar-legend'><div class='progress-bar-blue1'></div><div class='sp-content'>Hombres</div></div>
  <div class='progressbar-legend'><div class='progress-bar-blue6'></div><div class='sp-content'>Mujeres</div></div>
  </div>
</div>
</div>
</div>


-------------------------------------------------------------------------------------------------------------------------------------------------
<h1 style="color: #005980; margin: 15px;">Participación ciudadana y elecciones</h1>

```{r Convocatoria}
data_participacion <- fromJSON(params$url.participacion)

convocatoria <- data.frame(
    proceso = data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[2]][["id"]],
    name = vector(mode = "character", length = data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][2]))
for(i in 1:data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][2]) {
  convocatoria$name[i] <- data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[2]][["name"]][["text"]][[i]][["value"]]
}
```

```{r Participación}
dP <- length(rep(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
                 each = length(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                        length(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]]))) -
                        length(unlist(strsplit(data_participacion[["data"]][["observations"]], split = " | ", fixed = TRUE)))

###### Añadir aviso si la variable d_ es mayor que 0 ######

df_participacion_total <- data.frame(
  ind = rep(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[1]][["code"]],
            each = length(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]]) *
                   length(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  proceso = rep(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]])),
  mun = data_participacion[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[3]][["code"]],
  valor = c(unlist(strsplit(data_participacion[["data"]][["observations"]], split = " | ", fixed = TRUE)), rep(NA, dP)))
df_participacion_total$valor <- df_participacion_total$valor %>% as.numeric %>% round(1)
df_participacion_total <- recode_Frontera_electorales(df_participacion_total)
df_participacion_total$mun <- recode_id_Frontera(df_participacion_total, 'mun')

df_ind <- data.frame(
  ind = data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[1]][["id"]],
  indicador = vector(mode = "character", length = data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][1]),
  order = c(1:data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["total"]][1]))

for(i in 1:nrow(df_ind)) {
  df_ind$indicador[i] <- data_participacion[["metadata"]][["dimensions"]][["dimension"]][["dimensionValues"]][["value"]][[1]][["name"]][["text"]][[i]][["value"]]
}
df_ind$indicador <- factor(df_ind$indicador, levels = df_ind$indicador)
```


```{r Convocatoria autonómicas}
convocatoria_autonomicas <- convocatoria %>%
  filter(substring(proceso, 0,12) == "AUTONOMICAS_" & substring(proceso, 17,27) != "_REGIONALES") %>%
  transform(url = paste0("url.", tolower(substring(proceso, 0,16))))
convocatoria_autonomicas <- convocatoria_autonomicas %>%
  mutate(order = as.integer(order(1:nrow(convocatoria_autonomicas), decreasing = TRUE)),
         convocatoria_formatted = paste0(substring(proceso, 13,16)))
convocatoria_autonomicas <- convocatoria_autonomicas %>% arrange(order)
convocatoria_autonomicas$proceso <- factor(convocatoria_autonomicas$proceso, levels = convocatoria_autonomicas$proceso)

convocatoria_actual <- convocatoria_autonomicas %>% filter(order == max(order))
convocatoria_tva <- convocatoria_autonomicas %>% filter(order == max(order) - 1)
```

```{r Gráfico evolución autonómicas}
df_participacion <- df_participacion_total %>%
  filter(substring(proceso, 0,12) == "AUTONOMICAS_" &
         substring(proceso, 17,27) != "_REGIONALES" &
         proceso %notin% c("AUTONOMICAS_1983", "AUTONOMICAS_1987", "AUTONOMICAS_1991", "AUTONOMICAS_1995", "AUTONOMICAS_1999", "AUTONOMICAS_2003"))
df_u <- df_participacion %>% filter(substring(mun, 0,2) != "ES" & ind == "TASA_PARTICIPACION") %>% arrange(proceso) %>% select(!ind)

related_mun <- df_u %>% filter(proceso == convocatoria_actual$proceso)
related_mun <- seleccion_mun(related_mun %>% select(mun, valor), 'valor')

min_proceso <- min(df_u$proceso)
df <- related_mun %>%
  select(mun, nombre) %>%
  left_join(df_u, by = 'mun') %>%
  select(id = mun, proceso, valor, nombre) %>%
  left_join(df_CL_AREA_mun, by = 'id') %>%
  select(proceso, valor, id, nombre) %>%
  left_join(convocatoria_autonomicas, by = 'proceso') %>%
  filter(order > max(convocatoria_autonomicas$order) - 6) %>%
  transform(variacion = ifelse(proceso == min_proceso, NA, round((valor - lag(valor)), 1)))

min_order <- min(df$order)
max_order <- max(df$order)
I_Tasa_participacion_num <- df %>% filter(order == min_order) %>% select(valor) %>% as.numeric
I_Tasa_participacion <- I_Tasa_participacion_num %>% round(1) %>% format(big.mark = ".", decimal.mark = ",", nsmall = 1) %>% paste0("%")
Tasa_participacion_num <- df %>% filter(order == max_order) %>% select(valor) %>% as.numeric
Tasa_participacion <- Tasa_participacion_num %>% round(1) %>% format(big.mark = ".", decimal.mark = ",", nsmall = 1) %>% paste0("%")

df <- df %>%
  transform(hovertext = paste0(
    "<b>", nombre, "</b><br>Tasa de participación: ", ifelse(is.na(valor), " -", paste0(trimws(format(valor, big.mark = ".", decimal.mark = ",")), "%")),
    "<br>Variación: ", ifelse(is.na(variacion), " -", paste0(trimws(format(round(variacion, 1), big.mark = ".", decimal.mark = ",")), " puntos"))))

g_line_colours <- setNames(c('rgba(0, 89, 128, 0.8)', 'rgba(0, 139, 208, 0.8)', 'rgba(140, 210, 234, 0.8)'), related_mun$nombre)

g_line_el_a <- ggplot(data = df, aes(x = order, y = valor, group = nombre, colour = nombre, text = hovertext)) +
  geom_line(size = 0.7) +
  geom_text(aes(x = min_order+0.22, y = (0.92*I_Tasa_participacion_num), label = I_Tasa_participacion, colour = '#000000'), size = 3.5) +
  geom_text(aes(x = max_order-0.22, y = (0.94*Tasa_participacion_num), label = Tasa_participacion, colour = '#000000'), size = 3.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none") +
  scale_colour_manual(values = g_line_colours) +
  scale_size_manual(values = c(1, 0.1, 0.1)) +
  scale_x_continuous(breaks = function(x){min(df$order):max(df$order)},
                     labels = c(convocatoria_autonomicas$convocatoria_formatted[which(convocatoria_autonomicas$order %in% c(min(df$order):max(df$order)))])) +
  scale_y_continuous(labels = function(x) {paste0(format(x, big.mark = ".", decimal.mark = ","), "%")}, n.breaks = 6, limits = c(0, NA))

g_line_el_a <- ggplotly(g_line_el_a, tooltip = "text") %>%
  config(displaylogo = FALSE, modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>%
  layout(hoverlabel = "", hovermode = 'x unified',
         xaxis = list(autorange = FALSE,
                      range = c(max(min(df$order), max(df$order) - 8), max(df$order)))) %>%
  style(hoverinfo = "skip", traces = c(2, 3))
```

```{r Autonómicas, results='asis'}
df_participacion_mun <- df_participacion %>%
  filter(mun == params$id_municipio &
         ind %in% c('ELECTORES', 'VOTANTES', 'TASA_PARTICIPACION', 'TASA_ABSTENCION', 'TASA_VOTOS_VALIDOS', 'TASA_VOTOS_NULOS')) %>%
  left_join(convocatoria_autonomicas, by = 'proceso') %>%
  filter(order > max(convocatoria_autonomicas$order) - 4) %>%
  select(!order) %>%
  left_join(df_ind, by = 'ind') %>%
  mutate(valor = ifelse(ind == "ELECTORES", format(round(valor, 0), big.mark = ".", decimal.mark = ","),
                        ifelse(ind == "VOTANTES", format(round(valor, 0), big.mark = ".", decimal.mark = ","),
                               paste0(format(round(valor, 1), big.mark = ".", decimal.mark = ",", nsmall = 1), "%")))) %>%
  select(indicador, convocatoria_formatted, valor)
df_participacion_mun <- df_participacion_mun %>%
  acast(indicador ~ convocatoria_formatted)

tb_el_a <- df_participacion_mun %>%
  kable(format = 'html', align = 'c', table.attr = "class=\"my-table-2\"") %>%
  kable_styling(full_width = TRUE, position = "left") %>%
  column_spec(1:4, width = "15%")
```
<div class="highlight" style="width: 100% !important; margin: 15px 5px;">
<h2 style="color: #005980; margin-left: 20px;">Resultados de las Elecciones Autonómicas</h2>

<div class="row">
  <div class="column-2">`r tb_el_a`</div>
  
  <div class="column-2" style="height: 340px;">`r g_line_el_a`</div>
</div>
</div>

```{r Convocatoria municipales}
convocatoria_municipales <- convocatoria %>%
  filter(substring(proceso, 0,12) == "MUNICIPALES_") %>%
  transform(url = paste0("url.", tolower(proceso)))
convocatoria_municipales <- convocatoria_municipales %>%
  mutate(order = as.integer(order(1:nrow(convocatoria_municipales), decreasing = TRUE)),
         convocatoria_formatted = paste0(substring(proceso, 13,16)))
convocatoria_municipales <- convocatoria_municipales %>% arrange(order)
convocatoria_municipales$proceso <- factor(convocatoria_municipales$proceso, levels = convocatoria_municipales$proceso)

convocatoria_actual <- convocatoria_municipales %>% filter(order == max(order))
convocatoria_tva <- convocatoria_municipales %>% filter(order == max(order) - 1)
```

```{r Gráfico evolución municipales}
df_participacion <- df_participacion_total %>%
  filter(substring(proceso, 0,12) == "MUNICIPALES_" &
         proceso %notin% c("MUNICIPALES_1979", "MUNICIPALES_1983", "MUNICIPALES_1987", "MUNICIPALES_1991", "MUNICIPALES_1995", "MUNICIPALES_1999", "MUNICIPALES_2003"))
df_u <- df_participacion %>% filter(substring(mun, 0,2) != "ES" & ind == "TASA_PARTICIPACION") %>% arrange(proceso) %>% select(!ind)

related_mun <- df_u %>% filter(proceso == convocatoria_actual$proceso)
related_mun <- seleccion_mun(related_mun %>% select(mun, valor), 'valor')

min_proceso <- min(df_u$proceso)
df <- related_mun %>%
  select(mun, nombre) %>%
  left_join(df_u, by = 'mun') %>%
  select(id = mun, proceso, valor, nombre) %>%
  left_join(df_CL_AREA_mun, by = 'id') %>%
  select(proceso, valor, id, nombre) %>%
  left_join(convocatoria_municipales, by = 'proceso') %>%
  filter(order > max(convocatoria_municipales$order) - 6) %>%
  transform(variacion = ifelse(proceso == min_proceso, NA, round((valor - lag(valor)), 1)))

min_order <- min(df$order)
max_order <- max(df$order)
I_Tasa_participacion_num <- df %>% filter(order == min_order) %>% select(valor) %>% as.numeric
I_Tasa_participacion <- I_Tasa_participacion_num %>% round(1) %>% format(big.mark = ".", decimal.mark = ",", nsmall = 1) %>% paste0("%")
Tasa_participacion_num <- df %>% filter(order == max_order) %>% select(valor) %>% as.numeric
Tasa_participacion <- Tasa_participacion_num %>% round(1) %>% format(big.mark = ".", decimal.mark = ",", nsmall = 1) %>% paste0("%")

df <- df %>%
  transform(hovertext = paste0(
    "<b>", nombre, "</b><br>Tasa de participación: ", ifelse(is.na(valor), " -", paste0(trimws(format(valor, big.mark = ".", decimal.mark = ",")), "%")),
    "<br>Variación: ", ifelse(is.na(variacion), " -", paste0(trimws(format(round(variacion, 1), big.mark = ".", decimal.mark = ",")), " puntos"))))

g_line_colours <- setNames(c('rgba(0, 89, 128, 0.8)', 'rgba(0, 139, 208, 0.8)', 'rgba(140, 210, 234, 0.8)'), related_mun$nombre)

g_line_el_m <- ggplot(data = df, aes(x = order, y = valor, group = nombre, colour = nombre, text = hovertext)) +
  geom_line(size = 0.7) +
  geom_text(aes(x = min_order+0.22, y = (0.92*I_Tasa_participacion_num), label = I_Tasa_participacion, colour = '#000000'), size = 3.5) +
  geom_text(aes(x = max_order-0.22, y = (0.94*Tasa_participacion_num), label = Tasa_participacion, colour = '#000000'), size = 3.5) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "none") +
  scale_colour_manual(values = g_line_colours) +
  scale_size_manual(values = c(1, 0.1, 0.1)) +
  scale_x_continuous(breaks = function(x){min(df$order):max(df$order)},
                     labels = c(convocatoria_municipales$convocatoria_formatted[which(convocatoria_municipales$order %in% c(min(df$order):max(df$order)))])) +
  scale_y_continuous(labels = function(x) {paste0(format(x, big.mark = ".", decimal.mark = ","), "%")}, n.breaks = 6, limits = c(0, NA))

g_line_el_m <- ggplotly(g_line_el_m, tooltip = "text") %>%
  config(displaylogo = FALSE, modeBarButtons = list(list("zoom2d"),list("pan2d"),list("resetScale2d"),list("toImage"))) %>%
  layout(hoverlabel = "", hovermode = 'x unified',
         xaxis = list(autorange = FALSE,
                      range = c(max(min(df$order), max(df$order) - 8), max(df$order)))) %>%
  style(hoverinfo = "skip", traces = c(2, 3))
```

```{r Municipales, results='asis'}
df_participacion_mun <- df_participacion %>%
  filter(mun == params$id_municipio &
         ind %in% c('ELECTORES', 'VOTANTES', 'TASA_PARTICIPACION', 'TASA_ABSTENCION', 'TASA_VOTOS_VALIDOS', 'TASA_VOTOS_NULOS')) %>%
  left_join(convocatoria_municipales, by = 'proceso') %>%
  filter(order > max(convocatoria_municipales$order) - 4) %>%
  select(!order) %>%
  left_join(df_ind, by = 'ind') %>%
  mutate(valor = ifelse(ind == "ELECTORES", format(round(valor, 0), big.mark = ".", decimal.mark = ","),
                        ifelse(ind == "VOTANTES", format(round(valor, 0), big.mark = ".", decimal.mark = ","),
                               paste0(format(round(valor, 1), big.mark = ".", decimal.mark = ",", nsmall = 1), "%")))) %>%
  select(indicador, convocatoria_formatted, valor)
df_participacion_mun <- df_participacion_mun %>%
  acast(indicador ~ convocatoria_formatted)

tb_el_m <- df_participacion_mun %>%
  kable(format = 'html', align = 'c', table.attr = "class=\"my-table-2\"") %>%
  kable_styling(full_width = TRUE, position = "left") %>%
  column_spec(1:4, width = "15%")
```
<div class="highlight" style="width: 100% !important; margin: 15px 5px;">
<h2 style="color: #005980; margin-left: 20px;">Resultados de las Elecciones Municipales</h2>

<div class="row">
  <div class="column-2">`r tb_el_m`</div>
  
  <div class="column-2" style="height: 340px;">`r g_line_el_m`</div>
</div>
</div>

