---
title: "presupuestos_partidas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r librerías y funciones, include=FALSE}
list.of.packages <- c("jsonlite", "ggplot2", "knitr", "data.table", "plotly", "plyr", "dplyr", "scales", "htmlwidgets", "sf", "fuzzyjoin", "xml2", "XML", "tidyverse", "tmap", "magrittr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
sapply(list.of.packages, require, character.only = TRUE)

"%notin%" <- Negate("%in%")

recode_id_Frontera <- function(df, colname) {
  df[,colname] = trimws(df[,colname])
  df[,colname] = mapvalues(df[,colname], from = c("38013_1912", "38013_2007"), to = c("38013", "38013"))
  df[,colname]
}
```

```{r}
data_estr_partidas <- fromJSON(paste0("https://datos.canarias.es/api/estadisticas/statistical-resources/v1.0/datasets/ISTAC/E31025B_",sprintf ("%06.0f", 2020 - 2006), "/~latest.json?dim=TERRITORIO:35004|35010|35018|35024|35028|35029|35034|35003|35007|35014|35015|35017|35030|35001|35002|35005|35006|35008|35009|35011|35012|35013|35016|35019|35020|35021|35022|35023|35025|35026|35027|35031|35032|35033|38001|38004|38005|38006|38010|38011|38012|38015|38017|38018|38019|38020|38022|38023|38025|38026|38028|38031|38032|38034|38035|38038|38039|38040|38041|38042|38043|38044|38046|38051|38052|38002|38003|38021|38036|38049|38050|38007|38008|38009|38014|38016|38024|38027|38029|38030|38033|38037|38045|38047|38053|38013_2007|38048|38901:PRESUPUESTO_ESTADO:PRESUPUESTO_EJECUTADO:MEDIDAS:IMPORTE_PRESUPUESTARIO:PRESUPUESTO_PARTIDA:G_10|G_11|G_12|G_13|G_14|G_15|G_16|G_20|G_21|G_22|G_23|G_24|G_25|G_26|G_27|G_30|G_31|G_32|G_33|G_34|G_35|G_42|G_43|G_44|G_45|G_46|G_47|G_48|G_49|G_50|G_60|G_61|G_62|G_63|G_64|G_65|G_68|G_69|G_72|G_73|G_74|G_75|G_76|G_77|G_78|G_79|G_80|G_81|G_82|G_83|G_84|G_85|G_86|G_87|G_90|G_91|G_92|G_93|G_94|I_10|I_11|I_13|I_17|I_18|I_19|I_22|I_28|I_29|I_30|I_31|I_32|I_33|I_34|I_35|I_36|I_38|I_39|I_42|I_43|I_44|I_45|I_46|I_47|I_48|I_49|I_4T|I_50|I_51|I_52|I_53|I_54|I_55|I_59|I_60|I_61|I_68|I_72|I_73|I_74|I_75|I_76|I_77|I_78|I_79|I_7T|I_80|I_81|I_82|I_83|I_84|I_85|I_86|I_87|I_90|I_91|I_93|I_94|GASTOS|INGRESOS&lang=es"))
dp <- length(rep(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
                 each = length(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]]))) -
      length(unlist(strsplit(data_estr_partidas[["data"]][["observations"]], split = " | ", fixed = TRUE)))

###### Añadir aviso si la variable d_ es mayor que 0 ######

df_estr_partidas <- data.frame(
  mun = rep(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]],
            each = length(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]])),
  id_partida = rep(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[5]][["code"]],
                   times = length(data_estr_partidas[["data"]][["dimensions"]][["dimension"]][["representations"]][["representation"]][[2]][["code"]])),
  valor = c(unlist(strsplit(data_estr_partidas[["data"]][["observations"]], split = " | ", fixed = TRUE)), rep(NA, dp)))
df_estr_partidas$mun <- recode_id_Frontera(df_estr_partidas, 'mun')

df_estr_partidas_mun <- df_estr_partidas %>% filter(mun == 38038 & id_partida %notin% c("GASTOS", "INGRESOS")) %>% select(!mun)
```

```{r}
CL_PARTIDA <- as_list(read_xml("https://datos.canarias.es/api/estadisticas/structural-resources/v1.0/codelists/ISTAC/CL_PPTOS_ES_EELL_ESTRUCTURA_ECONOMICA/~latest/codes?limit=100000"))

df_CL_PARTIDA <- tibble::as_tibble(CL_PARTIDA) %>% 
  unnest_wider('codes') %>%
  unnest(cols = names(.)) %>%
  unnest(cols = names(.)) %>%
  readr::type_convert() %>%
  select(id, partida = name)

df_CL_PARTIDA_dos <- df_CL_PARTIDA %>%
  filter(nchar(id) == 4) %>%
  select(id_partida = id, partida)

url_partidas <- paste0("https://datos.canarias.es/api/estadisticas/structural-resources/v1.0/codelists/ISTAC/CL_PPTOS_ES_EELL_ESTRUCTURA_ECONOMICA/~latest/codes/",
                       df_estr_partidas_mun$id_partida)

df_partidas <- data.frame(matrix(ncol = 2, nrow = length(df_estr_partidas_mun$id_partida), dimnames = list(NULL, c("id_partida", "shortName"))))
for(i in 1:length(df_estr_partidas_mun$id_partida)) {
  df_partidas$id_partida[i] <- as_list(read_xml(url_partidas[i]))$code$id[[1]]
  df_partidas$shortName[i] <- as_list(read_xml(url_partidas[i]))$code$shortName$text[[1]]
}

df_partidas <- df_partidas %>%
  inner_join(df_CL_PARTIDA_dos, by = "id_partida")
for(i in 1:nrow(df_partidas)) {
  df_partidas$partida[i] <- df_partidas$partida[[i]][1]
}
df_partidas$partida <- as.character(df_partidas$partida)

write.csv2(df_partidas, file = "partidas.csv", row.names = FALSE, col.names = TRUE)

write.csv(df_partidas, "C:\\Users\\elois\\Desktop\\G\\partidas.csv", row.names = FALSE, col.names = TRUE)
write.csv2(df_partidas, "partidasss.csv", row.names = FALSE, col.names = TRUE)
write.csv2(df_CL_PARTIDA_dos, "partidasss.csv", row.names = FALSE, col.names = TRUE)
```

```{r}
df_CL_PARTIDA_dos
df_partidas
```

