---
title: "Selección de municipios para comparar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r librerias, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(jsonlite)
# library(RecordLinkage)
# library(lwgeom)
library(sf)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Distancia
# Latitud y longitud de los municipios:
urlmun <- "https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicatorsSystems/C00067A/indicatorsInstances/6daf4220-c08f-431c-8383-a0a7daa87da7"
datamun <- fromJSON(urlmun)
df_localizacion <- data.frame(mun = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["code"]],
                              nombre = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["title"]][["es"]],
                              latitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["latitude"]],
                              longitud = datamun[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["longitude"]]) %>% 
  filter(substring(mun, 0,2) != "ES")

## Población
# Población. Municipios por islas de Canarias y años:
urlp <- "https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicatorsSystems/C00067A/indicatorsInstances/6daf4220-c08f-431c-8383-a0a7daa87da7/data?representation=MEASURE%5BABSOLUTE%5D%2CTIME%5B2020%5D"
datap <- fromJSON(urlp)
df_poblacion <- data.frame(mun = names(datap[["dimension"]][["GEOGRAPHICAL"]][["representation"]][["index"]]), poblacion = datap[["observation"]])
df_poblacion$mun <- factor(df_poblacion$mun)
df_poblacion$poblacion <- as.double(gsub(',', '', df_poblacion$poblacion))
df_poblacion <- df_poblacion %>% filter(substring(mun, 0,2) != "ES")

df <- cbind(df_localizacion, df_poblacion$poblacion)
df_sf <- st_as_sf(df, coords = c("longitud", "latitud"), crs = 4326)
distancias_mun <- st_distance(df_sf)
distancias_mun <- distancias_mun / 1000

seleccion_mun <- function(df_localizacion, df_variable, p){
  mun_seleccionados <- NULL
  for(i in 1:88){
    df_dif <- data.frame(mun = df_localizacion$mun, nombre = df_localizacion$nombre,
                         # distancia = geosphere::distHaversine(c(df_localizacion[i,]$latitud, df_localizacion[i,]$longitud),
                         #                                      cbind(df_localizacion$latitud, df_localizacion$longitud)) / 1000,
                         distancia = as.numeric(distancias_mun[i,]),
                         dif_pob = abs(df_poblacion$poblacion - (df_poblacion[i,]$poblacion)))
    df_dif <- cbind(df_dif, coeficientes = p * df_dif$distancia + (1-p) * df_dif$dif_pob)
    df_dif <- df_dif %>% arrange(coeficientes)
    mun_seleccionados <- rbind.data.frame(mun_seleccionados,
                                          cbind(mun = df_localizacion$nombre[i],
                                                grupo_mun = df_dif[1:3,] %>% select(nombre) %>% as.list()))
  }
  rownames(mun_seleccionados) <- 1:88
  kableExtra::kable(mun_seleccionados, format = "simple", col.names = c("Municipio", "Grupo"))
}
```

### Peso de la población 0,9
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.9)
```

### Peso de la población 0,8
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.8)
```

### Peso de la población 0,7
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.7)
```

### Peso de la población 0,6
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.6)
```

### Peso de la población 0,5
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.5)
```

### Peso de la población 0,4
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.4)
```

### Peso de la población 0,3
```{r, echo=FALSE, message=FALSE, warning=FALSE}
seleccion_mun(df_localizacion, df_poblacion, 0.3)
```
